### ISSUE TITLE
OnChannelMessage never invoked

### ISSUE THREAD

**Issue by sgrassie** [alexhorner/smIRCL#2]
Hi, I've been testing this to write a small bot, as it's literally the only lib I can find with SASL support.

I'm finding that on this line:

https://github.com/alexhorner/smIRCL/blob/af1a40eb32a4c8927846b13a2c2b1cae1f8c61ec/smIRCL/Core/IrcController.StateHandlers.cs#L69

The `else` never gets hit, so the `OnChannelMessage` never gets hit. In my testing, I found that if I send a CTCP <nick or channel> VERSION, then `message.Parameters[1]` is actually `" VERSION"`.

**Comment by alexhorner** [comment]
.. Wow really? Okay, I didn't realise anyone had picked up on this little library!

I have a bunch of changes uncommitted (some breaking) so I will look at those tomorrow along with this to see what I can merge in for you

**Comment by alexhorner** [comment]
Just an update, I need to play with this a bit more before I can push something reasonable.

**Comment by alexhorner** [comment]
Hey @sgrassie

I have pushed source code to the master branch which should resolve this issue and also does a whole bunch of other changes which the library despirately needed, since I wrote it without as much experience as I have now,

If you could try this out, it would be much appreciated, thanks!

**Comment by sgrassie** [comment]
@alexhorner as I said, this is literally the only C# IRC library I could find with SASL support 😃 

I've updated my local copy with your latest changes, unfortunately I still see the same issue:

<img width="636" alt="Screenshot 2022-01-16 at 22 49 14" src="https://user-images.githubusercontent.com/194140/149681501-efa7fade-3d20-42f3-888e-32d67845f843.png">

I will idle in the channel on libera and try and catch you there to discuss it a bit more, possibly there is something in the way I'm initialising the connector/controller and hooking the events up which is causing it.
